name: CI

on:
  pull_request:

jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          cd 2021
          pip install -U pip wheel
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Run tests
        run: |
          cd 2021
          pytest