name: CI

on:
  pull_request:

jobs:
  hello_ci:
    name: salutation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Welcome
        run: |
          echo "Hello CI!"